apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-portal-api
spec:
  template:
    spec:
      containers:
        - name: customer-portal-api
          image: ghcr.io/ethio-connect-et/customer-portal-api@sha256:2222222222222222222222222222222222222222222222222222222222222222
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-portal-dashboard
spec:
  template:
    spec:
      containers:
        - name: customer-portal-dashboard
          image: ghcr.io/ethio-connect-et/customer-portal-dashboard@sha256:2222222222222222222222222222222222222222222222222222222222222222
