images:
  api:
    repository: ghcr.io/ethio-connect-et/customer-portal-api
    tag: main
    digest: ""
  dashboard:
    repository: ghcr.io/ethio-connect-et/customer-portal-dashboard
    tag: main
    digest: ""
