apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts
helmCharts:
  - name: vendor-portal
    releaseName: vendor-portal
    valuesFile: values/vendor-portal.yaml
  - name: customer-portal
    releaseName: customer-portal
    valuesFile: values/customer-portal.yaml
  - name: central-hub
    releaseName: central-hub
    valuesFile: values/central-hub.yaml
  - name: shared-infrastructure
    releaseName: shared-infrastructure
    valuesFile: values/shared-infrastructure.yaml
patches:
  - path: patch-staging-env.yaml
